import type { Metadata } from 'next'
import '@/styles/global.css'
import { Footer } from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'
import { ViewTransitions } from 'next-view-transitions'
import { M_PLUS_1p } from 'next/font/google'
import { cx } from 'styled-system/css'
import { flex, grid } from 'styled-system/patterns'

const MPlus1p = M_PLUS_1p({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang='ja'>
        <body className={MPlus1p.className}>
          <div
            className={cx(
              grid({
                minH: '100vh',
                gridTemplateRows: 'auto 1fr auto',
                rowGap: { base: '6rem', md: '8rem' },
              }),
            )}
          >
            <Header />
            <main
              className={flex({
                alignItems: 'start',
                justifyContent: 'center',
                px: { base: '2rem', md: 0 },
              })}
            >
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </ViewTransitions>
  )
}
